/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package memorygame;

import java.awt.Color;
import java.awt.Image;
import java.awt.List;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.ActionMap;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.BorderFactory;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author Alpe
 */
public class NewJFrame extends javax.swing.JFrame {

    public static String [] cuadros = {"Habitacion-VanGogh.jpg","ElNacimientoDeVenus-botticelli.jpg","ElBeso-Klimt.jpg","impresionista.jpg",
                                        "Leonardo_da_Vinci_Mona_Lisa.jpg","muchacha-en-ventana-dali.jpg","Leonardo_da_Vinci_Mona_Lisa.jpg","muchacha-en-ventana-dali.jpg",
                                        "Habitacion-VanGogh.jpg","ElNacimientoDeVenus-botticelli.jpg","ElBeso-Klimt.jpg","impresionista.jpg"};
    public static String ruta = "src\\memorygame\\img\\";
    public static JLabel[] etiquetas = new JLabel[12];
    public static String activo1 = "";
    public static JLabel lblAnterior;
    public static int marcador = 0;
    
    //public static Object [] marcos = new Object[12];
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();    
        
        //Cargar icono app
        String iconURL = ruta + "ico.png";
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        this.setResizable(false);
        
        cargarCuadros();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTablero = new javax.swing.JPanel();
        lblResultados = new javax.swing.JLabel();
        lblResultados1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelTablero.setBackground(new java.awt.Color(204, 204, 204));

        lblResultados.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        lblResultados.setForeground(new java.awt.Color(102, 0, 102));
        lblResultados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultados.setText("Bienvenido");

        lblResultados1.setFont(new java.awt.Font("Pristina", 0, 36)); // NOI18N
        lblResultados1.setForeground(new java.awt.Color(102, 0, 102));
        lblResultados1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultados1.setText("Memory Art Game");

        javax.swing.GroupLayout jPanelTableroLayout = new javax.swing.GroupLayout(jPanelTablero);
        jPanelTablero.setLayout(jPanelTableroLayout);
        jPanelTableroLayout.setHorizontalGroup(
            jPanelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTableroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblResultados1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                    .addComponent(lblResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8))
        );
        jPanelTableroLayout.setVerticalGroup(
            jPanelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTableroLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblResultados1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 383, Short.MAX_VALUE)
                .addComponent(lblResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jPanelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    
    public void cargarCuadros(){
        
        ArrayList<Integer> mylist = new ArrayList<Integer>();
        for (int i=0;i<12;i++){
            mylist.add(i);
        }
        Collections.shuffle(mylist); 
        
        int fila = 1;
        int lado = 100;
        int columna = 0;       
        for (int i=0;i<12;i++){
            if(i>3)
                fila = 2;
            if(i>7)
                fila = 3;
            String cuadro = cuadros[mylist.get(i)];
            ImageIcon ico = new ImageIcon( ruta + cuadro);
            
            /*Redimensionar la imagen*/
            Image image = ico.getImage(); 
            Image newimg = image.getScaledInstance(100, 100,  java.awt.Image.SCALE_SMOOTH);
            ImageIcon ico2 = new ImageIcon(newimg);
            /*fin*/

            etiquetas[i] = new JLabel("");
            etiquetas[i].setSize(lado, lado);
            etiquetas[i].setBorder(BorderFactory.createLineBorder(Color.WHITE, 5));
            etiquetas[i].setBackground(Color.BLACK);
            etiquetas[i].setLocation(columna*lado+100,fila*lado+10);
            etiquetas[i].setName(cuadro);
            
            etiquetas[i].addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    ((JLabel) e.getSource()).setIcon(ico2);
                    
                    Timer timer = new Timer(); 
                    TimerTask task1 = new TimerTask() {
                        public void run() {

                            if ("".equals(activo1)) {
                                activo1 = cuadro;
                                lblAnterior = (JLabel) e.getSource();
                            } else { //Comparar
                                if (activo1 == cuadro) {
                                    marcador++;
                                    if (marcador == 6) {
                                        lblResultados.setText("Enhorabuena");
                                    } else {
                                        lblResultados.setText("Son iguales");
                                    }
                                } else {
                                    ImageIcon icoVacio = new ImageIcon("");
                                    lblResultados.setText("Sigue intentando");
                                    //Se 'dan la vuelta' al del evento y al anterior
                                    ((JLabel) e.getSource()).setIcon(icoVacio);
                                    lblAnterior.setIcon(icoVacio);
                                }
                                activo1 = "";
                            }
                        }
                    };
                    timer.schedule(task1, 1000); 
                }
            });
            add(etiquetas[i]);
            jPanelTablero.add(etiquetas[i]);
            columna++;
            if(columna==4)
                columna =0;
        }
    }
    
 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelTablero;
    private javax.swing.JLabel lblResultados;
    private javax.swing.JLabel lblResultados1;
    // End of variables declaration//GEN-END:variables
}
